apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-yaml
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deployment-yaml
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70